version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ltdiabse
      DB_NAME: iabse
      FLASK_APP: app:create_app
      SECRET_KEY: ltdiabse
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: flask run --host=0.0.0.0

  db:
    image: mysql:8.0
    container_name: iabse_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ltd_iabse
      MYSQL_DATABASE: iabse
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d

volumes:
  mysql_data: