version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ltd_iabse
      DB_NAME: iabse
      FLASK_APP: app:create_app
      SECRET_KEY: ltdiabse
      REDIS_HOST: redis-14542.c265.us-east-1-2.ec2.redns.redis-cloud.com
      REDIS_PORT: 14542
      REDIS_PASSWORD: xnniFaO1zl2ytYGhovw9jllmZHsOsQjF
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: flask run --host=0.0.0.0
    networks:
      - flask_network

  db:
    image: mysql:8.0
    container_name: iabse_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ltd_iabse
      MYSQL_DATABASE: iabse
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - flask_network

  redis:
    image: redis:alpine
    container_name: flask_redis
    ports:
      - "6379:6379"
    networks:
      - flask_network

volumes:
  mysql_data:

networks:
  flask_network:
    driver: bridge